# path to samplesheet
samplesheet: samples.csv

library_fasta: sgrna_lib.fa

fastq_dir: fastqs

pdna_fastq: fastqs/pDNA_S1_L001_R1_001.fastq.gz

threads: 4

trimming:
  tso: AAGCAGTGGTATCAACGCAGAGTACATGGG
  sgrna_scaffold: GTTTAAGAGCTAAGCTGGAAACAGCATAGCAAGTTTAAAT
  u6_promoter: GTGGAAAGGACGAAACACCG
  error_rate: 0.2

cell_barcode:
  whitelist: assets/barcodes/3M-february-2018.txt.gz

dedup_method: unique # unique/percentile/cluster/adjacency/directional

target_regex: "sg\\d+_([^_]+)$"