name: featurebarcode-qc-snakemake
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - biopython
  - umi_tools
  - cutadapt
  - bowtie
  - samtools
  - pandas
  - r-base
  - r-plyr
  - bioconductor-biostrings
  - r-magrittr
  - r-tidyverse
  - r-scales
  - r-cowplot
  - r-ggrepel
  - r-domc
  - r-tidyverse
  - r-rmarkdown
  - r-knitr