$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  trimming:
    type: object
    properties:
      tso:
        type: string
        # pattern: [ACGTN]+
      sgrna_scaffold:
        type: string
        # pattern: [ACGTN]+
      u6_promoter:
        type: string
      error_rate:
        type: number
        # minimum: 0
        # maximum: 0.5

  cell_barcode:
    type: object
    properties:
      whitelist:
        type: string

  dedup_method:
    type: string
    enum:
      - unique
      - percentile
      - cluster
      - adjacency
      - directional

  fastq_dir:
    type: string

  pdna_fastq:
    type: string

  feature_ref:
    type: string

  samplesheet:
    type: string

  threads:
    type: integer

required:
  - fastq_dir
  # - pdna_fastq
  - feature_ref
  - samplesheet
  - threads
