# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: conda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          python-version: 3.6
          channels: bioconda,conda-forge,defaults
          environment-file: envs/conda.yaml         
          activate-environment: featurebarcode-qc-snakemake
      
      - name: snakemake
        uses: snakemake/snakemake-github-action@v1.13.0
        with:
          # Working directory for the execution
          directory: .test
          # Snakefile containing the workflow description
          snakefile: Snakefile
          # Additional Snakemake arguments to use
          args: # optional, default is 
          # Additional steps to prepare the workflow for execution
          stagein: # optional, default is 

      
